import {test,expect,type Page} from '@playwright/test';
import {setDateTime} from './controls';

const eventId='12121212-1212-4121-8121-121212121212';
async function login(page:Page,destination='/events/new'){await page.goto(`/login?returnTo=${encodeURIComponent(destination)}`);await page.getByLabel('Email or phone number').fill('alex@example.com');await page.getByLabel('Password',{exact:true}).fill('correct');await page.getByRole('button',{name:'Sign in',exact:true}).click();}

test.beforeEach(async({request})=>{await request.post('http://127.0.0.1:4100/__state',{data:{}});});

test('public listing has complete loading result and event detail states',async({page})=>{await page.goto('/events');await expect(page.getByRole('heading',{name:'Rooms worth walking into.'})).toBeVisible();await expect(page.getByRole('heading',{name:'Builders over coffee'})).toBeVisible();await expect(page.getByText('Free',{exact:true})).toBeVisible();await page.getByRole('link',{name:'Builders over coffee',exact:true}).click();await expect(page.getByRole('heading',{name:'Builders over coffee'})).toBeVisible();await expect(page.getByRole('link',{name:'Sign in to register'})).toBeVisible();await expect(page.locator('body')).not.toContainText('PRIVATE_ROOM_SENTINEL');});

test('host creates an event with bounded capacity and listing visibility',async({page})=>{await login(page);await expect(page).toHaveURL('/events/new');await page.getByLabel('Event title').fill('Founders and operators');await page.getByLabel('Description').fill('Trade useful lessons from the work.');await setDateTime(page, 'Starts at', '2026-10-20', '18:30');await page.getByLabel('Capacity').fill('25');await page.getByRole('button',{name:'Create event'}).click();await expect(page).toHaveURL(/\/events\/[0-9a-f-]{36}$/);await expect(page.getByRole('heading',{name:'Founders and operators'})).toBeVisible();});

test('signed-in attendee registers and enters through the shared call surface',async({page})=>{await login(page,`/events/${eventId}`);await page.getByRole('button',{name:'Register'}).click();await expect(page.getByRole('heading',{name:'You’re registered'})).toBeVisible();await page.getByRole('link',{name:'Enter event'}).click();await page.route('https://livekit.test/**',route=>route.abort());await page.routeWebSocket('wss://livekit.test/**',()=>{});await page.getByRole('button',{name:'Enter event'}).click();await expect(page.getByRole('heading',{name:'Participants'})).toBeVisible();await expect(page.getByText('ordered for you')).toBeVisible();await expect(page.getByRole('button',{name:'Start spotlight queue'})).toHaveCount(0);await page.getByRole('button',{name:'Leave'}).click();await expect(page.getByRole('heading',{name:'You left the event'})).toBeVisible();});

test('host starts the room and receives the limited spotlight control',async({page,request})=>{await request.post('http://127.0.0.1:4100/__state',{data:{events:[{id:eventId,kind:'EVENT',hostId:'user-1',title:'Host room',description:'Hosted',startsAt:'2026-09-20T18:00:00.000Z',listed:true,priceCents:0,currency:'cad',status:'OPEN'}]}});await login(page,`/events/${eventId}`);await page.getByRole('link',{name:'Start event'}).click();await page.route('https://livekit.test/**',route=>route.abort());await page.routeWebSocket('wss://livekit.test/**',()=>{});await page.getByRole('button',{name:'Enter event'}).click();await expect(page.getByRole('button',{name:'Start spotlight queue'})).toBeVisible();await expect(page.getByRole('button',{name:/moderate|remove|mute/i})).toHaveCount(0);});

test('paid event explains unavailable checkout instead of claiming registration',async({page,request})=>{await request.post('http://127.0.0.1:4100/__state',{data:{events:[{id:eventId,kind:'EVENT',hostId:'user-1',title:'Paid room',description:'Ticketed',startsAt:'2026-09-20T18:00:00.000Z',listed:true,priceCents:2500,currency:'cad',status:'OPEN'}]}});await page.goto(`/events/${eventId}`);await expect(page.getByText('$25.00')).toBeVisible();await expect(page.getByRole('button',{name:'Registration unavailable'})).toBeDisabled();});

test('listing stacks without horizontal overflow on a phone',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/events');await expect(page.getByRole('heading',{name:'Builders over coffee'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});
