'use client';
import {useEffect,useState} from 'react';
import {api,ApiError,startCrmOAuth} from '@/lib/api';
import { isLiveConnection } from '@/lib/contracts';
import type {CalendarConnection,Engagement,Person,Pipeline,Stage} from '@/lib/contracts';
import Modal from './Modal';
import {DatePicker} from '@/components/ui/date-picker';
import {TimePicker} from '@/components/ui/time-picker';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';

export type InviteTarget={email:string;person?:Person;engagementId?:string};
type Mail={connectionId:string;provider:'GOOGLE'|'MICROSOFT';canSend:boolean;senderAddress?:string;mailStatus:string};
type Preview={target:InviteTarget;engagementId:string;idempotencyKey:string;draft:Record<string,unknown>;subject:string;html:string;from:string;to:string};
type Slot={date:string;time:string;duration:string};
const localZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
const displayName=(email:string)=>email.split('@')[0].replace(/[._-]+/g,' ').replace(/\b\w/g,char=>char.toUpperCase())||email;

export default function BulkOutreachComposer({workspaceId,targets,pipeline,stages,onClose,onSent}:{workspaceId:string;targets:InviteTarget[];pipeline:Pipeline;stages:Stage[];onClose:()=>void;onSent:()=>void}){
 const [connections,setConnections]=useState<CalendarConnection[]>();const [mails,setMails]=useState<Mail[]>([]);const [connectionId,setConnectionId]=useState('');const [problem,setProblem]=useState('');const [working,setWorking]=useState('');
 const [purpose,setPurpose]=useState('Coffee chat');const [message,setMessage]=useState('');const [timezone,setTimezone]=useState(localZone());const [venue,setVenue]=useState<'CAFFRIEND_LIVEKIT'|'PROVIDER_CONFERENCE'>('CAFFRIEND_LIVEKIT');const [slots,setSlots]=useState<Slot[]>([{date:'',time:'',duration:'30'}]);const [previews,setPreviews]=useState<Preview[]>();const [previewIndex,setPreviewIndex]=useState(0);const [results,setResults]=useState<{email:string;ok:boolean;error?:string}[]>();
 useEffect(()=>{let live=true;api<CalendarConnection[]>(`workspaces/${workspaceId}/calendar-connections`).then(async rows=>{if(!live)return;setConnections(rows);const statuses=await Promise.all(rows.filter(row=>isLiveConnection(row.status)).map(row=>api<Mail>(`workspaces/${workspaceId}/mail-connections/${row.id}`).catch(()=>({connectionId:row.id,provider:row.provider,canSend:false,mailStatus:'UNAVAILABLE'}))));if(!live)return;setMails(statuses);const usable=statuses.filter(row=>row.canSend);if(usable.length===1)setConnectionId(usable[0].connectionId);}).catch(error=>setProblem(error instanceof ApiError?error.message:'Connections could not be loaded.'));return()=>{live=false};},[workspaceId]);
 const selected=connections?.find(row=>row.id===connectionId);const usable=mails.filter(row=>row.canSend);const invalidate=()=>setPreviews(undefined);
 async function connectCalendar(){setWorking('connect');try{window.location.assign(await startCrmOAuth(`/workspaces/${workspaceId}/calendar-connections/GOOGLE/connect`));}catch(error){setProblem(error instanceof ApiError?error.message:'Google Calendar could not be connected.');setWorking('');}}
 async function connectMail(id:string){setWorking('connect');try{window.location.assign(await startCrmOAuth(`/workspaces/${workspaceId}/mail-connections/${id}/connect`));}catch(error){setProblem(error instanceof ApiError?error.message:'Mailbox permission could not be connected.');setWorking('');}}
 async function tracked(target:InviteTarget){let person=target.person;if(!person){person=await api<Person>(`workspaces/${workspaceId}/crm/people`,{method:'POST',body:JSON.stringify({displayName:displayName(target.email),email:target.email,sourceCategory:'MANUAL'}),headers:{'X-Idempotency-Key':crypto.randomUUID()}});}if(target.engagementId)return{person,engagementId:target.engagementId};const stage=stages.find(row=>row.name.toLowerCase()==='prospect')??stages.find(row=>!row.archived);if(!stage)throw new Error('The Prospect pipeline step is unavailable.');const engagement=await api<Engagement>(`workspaces/${workspaceId}/crm/engagements`,{method:'POST',body:JSON.stringify({pipelineId:pipeline.id,stageId:stage.id,status:'OPEN',objective:purpose.trim(),nextAction:'Invitation sent',personId:person.id}),headers:{'X-Idempotency-Key':crypto.randomUUID()}});return{person,engagementId:engagement.id};}
 function parsedSlots(){return slots.map(slot=>{const start=new Date(`${slot.date}T${slot.time}`);return{startsAt:start.toISOString(),endsAt:new Date(start.getTime()+Number(slot.duration)*60000).toISOString()};});}
 async function preview(){if(!message.trim()||!purpose.trim()||!connectionId||slots.some(slot=>!slot.date||!slot.time)){setProblem('Complete the purpose, message, sender account, and every proposed time.');return;}setWorking('preview');setProblem('');try{const times=parsedSlots();if(times.some(slot=>Date.parse(slot.startsAt)<=Date.now()))throw new Error('Every proposed time must be in the future.');const rendered:Preview[]=[];for(const target of targets){const record=await tracked(target);const draft={engagementId:record.engagementId,connectionId,recipientEmail:target.email,purpose:purpose.trim(),message:message.trim(),timezone,venue,slots:times};const email=await api<Omit<Preview,'target'|'engagementId'|'idempotencyKey'|'draft'>>(`workspaces/${workspaceId}/meeting-outreach/preview`,{method:'POST',body:JSON.stringify(draft)});rendered.push({...email,target:{...target,person:record.person,engagementId:record.engagementId},engagementId:record.engagementId,idempotencyKey:crypto.randomUUID(),draft});}setPreviews(rendered);setPreviewIndex(0);}catch(error){setProblem(error instanceof ApiError||error instanceof Error?error.message:'The previews could not be created. Nothing was sent.');}finally{setWorking('');}}
 async function sendAll(){if(!previews)return;setWorking('send');const sent=[] as {email:string;ok:boolean;error?:string}[];for(const item of previews){try{const result=await api<{sendStatus:string;sendErrorCode?:string}>(`workspaces/${workspaceId}/meeting-outreach`,{method:'POST',body:JSON.stringify(item.draft),headers:{'X-Idempotency-Key':item.idempotencyKey}});if(result.sendStatus!=='SENT')throw new Error(result.sendErrorCode||'Delivery could not be confirmed');await api(`workspaces/${workspaceId}/crm/notes`,{method:'POST',body:JSON.stringify({body:`Coffee chat invitation sent to ${item.to}.`,personId:item.target.person?.id,engagementId:item.engagementId}),headers:{'X-Idempotency-Key':crypto.randomUUID()}});sent.push({email:item.to,ok:true});}catch(error){sent.push({email:item.to,ok:false,error:error instanceof Error?error.message:'Send failed'});}}setResults(sent);setWorking('');onSent();}
 if(results)return <Modal title="Invitation delivery" onClose={onClose}><ul className="delivery-results">{results.map(row=><li key={row.email} className={row.ok?'sent':'failed'}><div><span className="result-label">Recipient</span><strong>{row.email}</strong></div><div><span className="result-label">Status</span><span>{row.ok?'Invitation sent':row.error}</span></div></li>)}</ul><div className="modal-actions delivery-actions"><button onClick={onClose}>Done</button></div></Modal>;
 // Same rule as the single composer: the mail grant is its own consent step and
 // does not wait on a calendar being chosen, so do not hide the button behind
 // CONNECTED and leave the gate with nothing to press.
 const mailable=(connections??[]).filter(row=>isLiveConnection(row.status));
 const pendingCalendars=(connections??[]).filter(row=>row.status==='SELECT_CALENDAR');
 const shown=previews?.[previewIndex];
 return <Modal title={`Create coffee chat invitation${targets.length>1?'s':''}`} description={`${targets.length} recipient${targets.length===1?'':'s'} · each person receives a private invitation`} onClose={onClose} wide>
  <div className="steps compose-steps" aria-hidden="true"><span className="on"/><span className={shown?'on':''}/></div>
  {!connections?<p role="status">Checking calendar and mailbox access…</p>:shown?null:<form className="outreach-form" onSubmit={event=>{event.preventDefault();preview();}}>{problem&&<p role="alert">{problem}</p>}
   {!connections.length?<div className="connection-gate"><strong>Connect Google Calendar</strong><p>Connect once to propose available times and authorize your mailbox.</p><button type="button" onClick={connectCalendar}>Connect Google Calendar</button></div>:!usable.length?<div className="connection-gate"><strong>Connect your mailbox to send</strong><p>Caffriend sends these invitations from your own address.</p>{mailable.map(row=><button type="button" key={row.id} onClick={()=>connectMail(row.id)}>Connect {row.accountIdentifier||row.provider} mailbox</button>)}{!!pendingCalendars.length&&<p className="small">{pendingCalendars.length===1?'Your calendar connection still needs a calendar chosen':'Some calendar connections still need a calendar chosen'} — finish that in <a href={`/app/${workspaceId}/settings`}>Calendars</a>.</p>}{!mailable.length&&<><p className="small">None of your connections can authorize a mailbox. Reconnect Google Calendar and try again.</p><button type="button" onClick={connectCalendar}>Connect Google Calendar</button></>}</div>:<>
    <div className="recipient-summary"><strong>Recipients</strong><div>{targets.map(target=><span className="recipient-pill" key={target.email}>{target.person?.displayName||target.email}</span>)}</div></div>
    <div className="field"><span className="field-label">From account</span><Select value={connectionId} onValueChange={value=>{setConnectionId(value);invalidate();}}><SelectTrigger aria-label="From account"><SelectValue placeholder="Choose a mailbox"/></SelectTrigger><SelectContent>{usable.map(mail=><SelectItem key={mail.connectionId} value={mail.connectionId}>{mail.senderAddress||mail.provider}</SelectItem>)}</SelectContent></Select></div>
    <label>Purpose<input required maxLength={2000} value={purpose} onChange={event=>{setPurpose(event.target.value);invalidate();}}/></label><label>Message<textarea required rows={5} maxLength={4000} value={message} onChange={event=>{setMessage(event.target.value);invalidate();}}/></label><label>Timezone<input value={timezone} onChange={event=>{setTimezone(event.target.value);invalidate();}}/></label>
    <fieldset><legend>Where will it happen?</legend><label className="choice"><input type="radio" checked={venue==='CAFFRIEND_LIVEKIT'} onChange={()=>{setVenue('CAFFRIEND_LIVEKIT');invalidate();}}/> Caffriend call</label><label className="choice"><input type="radio" checked={venue==='PROVIDER_CONFERENCE'} onChange={()=>{setVenue('PROVIDER_CONFERENCE');invalidate();}}/> Google Meet</label></fieldset>
    {venue==='PROVIDER_CONFERENCE'&&selected?.provider!=='GOOGLE'&&<div className="connection-gate"><strong>Google Meet needs a Google Calendar</strong><p>Your venue will not be changed automatically.</p><button type="button" onClick={connectCalendar}>Connect Google Calendar</button></div>}
    <fieldset><legend>Proposed times</legend>{slots.map((slot,index)=><div className="slot-row" key={index}><div className="field"><span className="field-label">Date</span><DatePicker aria-label="Date" value={slot.date} onChange={date=>{setSlots(rows=>rows.map((row,i)=>i===index?{...row,date}:row));invalidate();}}/></div><div className="field"><span className="field-label">Time</span><TimePicker aria-label="Time" value={slot.time} onChange={time=>{setSlots(rows=>rows.map((row,i)=>i===index?{...row,time}:row));invalidate();}}/></div><div className="field"><span className="field-label">Duration</span><Select value={slot.duration} onValueChange={duration=>{setSlots(rows=>rows.map((row,i)=>i===index?{...row,duration}:row));invalidate();}}><SelectTrigger aria-label="Duration"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="15">15 min</SelectItem><SelectItem value="30">30 min</SelectItem><SelectItem value="45">45 min</SelectItem><SelectItem value="60">1 hour</SelectItem></SelectContent></Select></div>{slots.length>1&&<button type="button" className="secondary small-button" onClick={()=>{setSlots(rows=>rows.filter((_,i)=>i!==index));invalidate();}}>Remove</button>}</div>)}{slots.length<5&&<button type="button" className="add-time" onClick={()=>{setSlots(rows=>[...rows,{date:'',time:'',duration:'30'}]);invalidate();}}>＋ Add another time {slots.length}/5</button>}</fieldset>
    <button disabled={!!working||venue==='PROVIDER_CONFERENCE'&&selected?.provider!=='GOOGLE'}>{working==='preview'?`Rendering ${targets.length} emails…`:'Preview emails'}</button></>}</form>}
  {shown&&<section className="email-preview" aria-label="Email preview">
   <header className="preview-head"><button type="button" className="link back" onClick={()=>setPreviews(undefined)}>← Back to editing</button><div><h3>Step 2 · Review each real email</h3><p className="small">Pick a recipient to see exactly what they will receive. Nothing has been sent yet.</p></div></header>
   <div className="preview-tabs" role="tablist" aria-label="Recipient previews">{previews!.map((item,index)=><button type="button" role="tab" aria-selected={index===previewIndex} className={index===previewIndex?'':'secondary'} key={item.to} onClick={()=>setPreviewIndex(index)}>{item.to}</button>)}</div>
   <dl><dt>From</dt><dd>{shown.from}</dd><dt>To</dt><dd>{shown.to}</dd><dt>Subject</dt><dd>{shown.subject}</dd></dl>
   <iframe title={`Actual invitation email for ${shown.to}`} sandbox="" srcDoc={shown.html}/>
   <div className="modal-actions preview-actions"><button type="button" className="secondary" onClick={()=>setPreviews(undefined)}>Edit</button><button type="button" disabled={!!working} onClick={sendAll}>{working==='send'?'Sending…':`Send ${previews!.length} invitation${previews!.length===1?'':'s'}`}</button></div>
  </section>}
 </Modal>;
}
