'use client';
import {useEffect,useMemo,useState} from 'react';
import {api,ApiError} from '@/lib/api';
import type {CalendarConnection,Person} from '@/lib/contracts';
import Modal from './Modal';
import {DatePicker} from '@/components/ui/date-picker';
import {TimePicker} from '@/components/ui/time-picker';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';

type MailStatus={connectionId:string;provider:'GOOGLE'|'MICROSOFT';canSend:boolean;senderAddress?:string;mailStatus:string};
type SlotDraft={date:string;time:string;duration:string};
type Preview={subject:string;html:string;text:string;from:string;to:string;previewToken:string};
type Draft={engagementId:string;connectionId:string;recipientEmail:string;purpose:string;message:string;timezone:string;venue:'CAFFRIEND_LIVEKIT'|'PROVIDER_CONFERENCE';slots:{startsAt:string;endsAt:string}[]};
const zones=()=>{const local=Intl.DateTimeFormat().resolvedOptions().timeZone;return [local,...['UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Europe/London','Europe/Berlin','Asia/Kolkata','Asia/Singapore','Australia/Sydney'].filter(zone=>zone!==local)];};
const blankSlot=():SlotDraft=>({date:'',time:'',duration:'30'});

export default function OutreachComposer({workspaceId,engagementId,person,initialPurpose,onClose,onSent}:{workspaceId:string;engagementId:string;person?:Person;initialPurpose:string;onClose:()=>void;onSent:()=>void}){
 const [connections,setConnections]=useState<CalendarConnection[]>();const [mails,setMails]=useState<MailStatus[]>([]);const [loading,setLoading]=useState(true);
 const [connectionId,setConnectionId]=useState('');const [recipientEmail,setRecipientEmail]=useState(person?.email??'');const [purpose,setPurpose]=useState(initialPurpose);const [message,setMessage]=useState('');const [timezone,setTimezone]=useState(zones()[0]);const [venue,setVenue]=useState<Draft['venue']>('CAFFRIEND_LIVEKIT');const [slots,setSlots]=useState<SlotDraft[]>([blankSlot()]);
 const [preview,setPreview]=useState<Preview>();const [problem,setProblem]=useState('');const [busy,setBusy]=useState<'preview'|'send'|'connect'|'revoke'>();const [sent,setSent]=useState(false);
 const [timelineWarning,setTimelineWarning]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const rows=await api<CalendarConnection[]>(`workspaces/${workspaceId}/calendar-connections`);if(!active)return;setConnections(rows);const states=await Promise.all(rows.filter(row=>row.status==='CONNECTED'||row.status==='SELECT_CALENDAR').map(row=>api<MailStatus>(`workspaces/${workspaceId}/mail-connections/${row.id}`).catch(()=>({connectionId:row.id,provider:row.provider,canSend:false,mailStatus:'UNAVAILABLE'} as MailStatus))));if(!active)return;setMails(states);const activeMail=states.filter(row=>row.canSend);setConnectionId(activeMail.length===1?activeMail[0].connectionId:'');}catch(error){if(active)setProblem(error instanceof ApiError?error.message:'Connections could not be loaded.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[workspaceId]);
 const invalidate=()=>setPreview(undefined);
 const selected=connections?.find(row=>row.id===connectionId);const mail=mails.find(row=>row.connectionId===connectionId);const activeMails=mails.filter(row=>row.canSend);const googleConnections=(connections??[]).filter(row=>row.provider==='GOOGLE'&&row.status==='CONNECTED');
 // The mail grant is its own consent round trip and the backend accepts it for any
 // live connection — a calendar still waiting to be chosen included. Filtering this
 // to CONNECTED left the gate with no button at all and no way forward.
 const mailable=(connections??[]).filter(row=>row.status==='CONNECTED'||row.status==='SELECT_CALENDAR');
 const pendingCalendars=(connections??[]).filter(row=>row.status==='SELECT_CALENDAR');
 const draft=useMemo<Draft|null>(()=>{const parsed=slots.map(slot=>{const start=new Date(`${slot.date}T${slot.time}`);const end=new Date(start.getTime()+Number(slot.duration)*60000);return Number.isFinite(start.getTime())?{startsAt:start.toISOString(),endsAt:end.toISOString()}:null;});if(!connectionId||!recipientEmail||!purpose.trim()||!message.trim()||parsed.some(slot=>!slot))return null;return{engagementId,connectionId,recipientEmail:recipientEmail.trim(),purpose:purpose.trim(),message:message.trim(),timezone,venue,slots:parsed as Draft['slots']};},[connectionId,recipientEmail,purpose,message,timezone,venue,slots,engagementId]);
 const changeSlot=(index:number,patch:Partial<SlotDraft>)=>{setSlots(current=>current.map((slot,i)=>i===index?{...slot,...patch}:slot));invalidate();};
 async function connectCalendar(){setBusy('connect');setProblem('');try{const result=await api<{redirect:string}>(`workspaces/${workspaceId}/calendar-connections/GOOGLE/connect`,{method:'POST',body:'{}'});window.location.assign(result.redirect);}catch(error){setProblem(error instanceof ApiError?error.message:'Google Calendar could not be connected.');setBusy(undefined);}}
 async function connectMail(id:string){setBusy('connect');setProblem('');try{const result=await api<{redirect:string}>(`workspaces/${workspaceId}/mail-connections/${id}/connect`,{method:'POST',body:'{}'});window.location.assign(result.redirect);}catch(error){setProblem(error instanceof ApiError?error.message:'Mailbox permission could not be connected.');setBusy(undefined);}}
 async function revokeMail(){if(!connectionId)return;setBusy('revoke');setProblem('');try{await api(`workspaces/${workspaceId}/mail-connections/${connectionId}/revoke`,{method:'POST',body:'{}'});setMails(rows=>rows.map(row=>row.connectionId===connectionId?{...row,canSend:false,mailStatus:'REVOKED',senderAddress:undefined}:row));setConnectionId('');invalidate();}catch(error){setProblem(error instanceof ApiError?error.message:'Mailbox permission could not be revoked.');}finally{setBusy(undefined);}}
 async function renderPreview(){if(!draft){setProblem('Complete the recipient, purpose, message, sender account, and every proposed time.');return;}if(draft.slots.some(slot=>Date.parse(slot.startsAt)<=Date.now())){setProblem('Every proposed time must be in the future.');return;}setBusy('preview');setProblem('');try{setPreview(await api<Preview>(`workspaces/${workspaceId}/meeting-outreach/preview`,{method:'POST',body:JSON.stringify(draft)}));}catch(error){setProblem(error instanceof ApiError?error.message:'The email preview could not be created. Nothing was sent.');}finally{setBusy(undefined);}}
 async function send(){if(!draft||!preview)return;setBusy('send');setProblem('');try{const result=await api<{sendStatus:string;sendErrorCode?:string}>(`workspaces/${workspaceId}/meeting-outreach`,{method:'POST',body:JSON.stringify(draft),headers:{'X-Idempotency-Key':crypto.randomUUID()}});if(result.sendStatus!=='SENT')throw new Error(result.sendErrorCode?`Delivery status: ${result.sendErrorCode}`:'Delivery could not be confirmed.');try{await api(`workspaces/${workspaceId}/crm/notes`,{method:'POST',body:JSON.stringify({body:`Coffee-chat invitation sent to ${draft.recipientEmail}.`,engagementId,...(person?{personId:person.id}:{})}),headers:{'X-Idempotency-Key':crypto.randomUUID()}});}catch{setTimelineWarning(true);}setSent(true);onSent();}catch(error){setProblem(error instanceof ApiError||error instanceof Error?error.message:'The invitation was not sent.');}finally{setBusy(undefined);}}
 if(sent)return <Modal title="Invitation sent" onClose={onClose}><p className="notice">The coffee-chat invitation was sent to {recipientEmail}{timelineWarning?'.':' and recorded on this engagement.'}</p>{timelineWarning&&<p role="alert">The invitation was delivered, but its timeline note could not be added. Refresh the engagement before trying to record it manually.</p>}<button onClick={onClose}>Done</button></Modal>;
 return <Modal title="Send coffee chat invite" description="Propose up to five times. Nothing is sent until you review the real email." onClose={onClose} wide>
  {loading?<p role="status">Checking your calendar and mailbox connections…</p>:<form className="outreach-form" onSubmit={event=>{event.preventDefault();renderPreview();}}>
   {problem&&<p role="alert">{problem}</p>}
   {!connections?.length&&<div className="connection-gate"><strong>Connect Google Calendar</strong><p>A calendar connection is needed to hold your mailbox permission and proposed availability.</p><button type="button" disabled={!!busy} onClick={connectCalendar}>{busy==='connect'?'Opening Google…':'Connect Google Calendar'}</button></div>}
   {!!connections?.length&&activeMails.length===0&&<div className="connection-gate"><strong>Connect your mailbox to send</strong><p>You cannot send an invitation until Caffriend has permission to send from your own mailbox.</p>{mailable.map(row=><button type="button" key={row.id} disabled={!!busy} onClick={()=>connectMail(row.id)}>Connect {row.accountIdentifier||row.provider} mailbox</button>)}{!!pendingCalendars.length&&<p className="small">{pendingCalendars.length===1?'Your calendar connection still needs a calendar chosen':'Some calendar connections still need a calendar chosen'} — finish that in <a href={`/app/${workspaceId}/settings`}>Calendars</a>.</p>}{!mailable.length&&<><p className="small">None of your connections can authorize a mailbox. Reconnect Google Calendar and try again.</p><button type="button" disabled={!!busy} onClick={connectCalendar}>{busy==='connect'?'Opening Google…':'Connect Google Calendar'}</button></>}</div>}
   {activeMails.length>0&&<>
    <div className="field"><span className="field-label">From account</span><Select value={connectionId} onValueChange={value=>{setConnectionId(value);invalidate();}}><SelectTrigger aria-label="From account"><SelectValue placeholder="Choose the mailbox"/></SelectTrigger><SelectContent>{activeMails.map(row=><SelectItem key={row.connectionId} value={row.connectionId}>{row.senderAddress||row.provider}</SelectItem>)}</SelectContent></Select></div>
    {mail&&<p className="small">Mailbox connected as {mail.senderAddress}. <button className="link" type="button" disabled={!!busy} onClick={revokeMail}>{busy==='revoke'?'Revoking…':'Revoke permission'}</button></p>}
    <label>Recipient email<input type="email" required maxLength={320} value={recipientEmail} onChange={e=>{setRecipientEmail(e.target.value);invalidate();}}/></label>
    <label>Purpose<input required maxLength={2000} value={purpose} onChange={e=>{setPurpose(e.target.value);invalidate();}}/></label>
    <label>Message<textarea required maxLength={4000} rows={4} value={message} onChange={e=>{setMessage(e.target.value);invalidate();}}/></label>
    <div className="field"><span className="field-label">Timezone</span><Select value={timezone} onValueChange={value=>{setTimezone(value);invalidate();}}><SelectTrigger aria-label="Timezone"><SelectValue placeholder="Choose a timezone"/></SelectTrigger><SelectContent>{zones().map(zone=><SelectItem key={zone} value={zone}>{zone}</SelectItem>)}</SelectContent></Select></div>
    <fieldset><legend>Where will the call happen?</legend><label className="choice"><input type="radio" checked={venue==='CAFFRIEND_LIVEKIT'} onChange={()=>{setVenue('CAFFRIEND_LIVEKIT');invalidate();}}/> Caffriend call</label><label className="choice"><input type="radio" checked={venue==='PROVIDER_CONFERENCE'} onChange={()=>{setVenue('PROVIDER_CONFERENCE');invalidate();}}/> Google Meet</label></fieldset>
    {venue==='PROVIDER_CONFERENCE'&&selected?.provider!=='GOOGLE'&&<div className="connection-gate"><strong>Google Meet needs a Google mailbox and calendar</strong><p>The requested venue will not be switched. {googleConnections.length?'Choose a connected Google mailbox above.':'Connect Google Calendar before previewing.'}</p>{!googleConnections.length&&<button type="button" disabled={!!busy} onClick={connectCalendar}>Connect Google Calendar</button>}</div>}
    <fieldset><legend>Proposed times</legend>{slots.map((slot,index)=><div className="slot-row" key={index}><div className="field"><span className="field-label">Date</span><DatePicker aria-label="Date" value={slot.date} onChange={date=>changeSlot(index,{date})}/></div><div className="field"><span className="field-label">Time</span><TimePicker aria-label="Time" value={slot.time} onChange={time=>changeSlot(index,{time})}/></div><div className="field"><span className="field-label">Duration</span><Select value={slot.duration} onValueChange={duration=>changeSlot(index,{duration})}><SelectTrigger aria-label="Duration"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="15">15 min</SelectItem><SelectItem value="30">30 min</SelectItem><SelectItem value="45">45 min</SelectItem><SelectItem value="60">1 hour</SelectItem></SelectContent></Select></div>{slots.length>1&&<button type="button" className="secondary small-button" onClick={()=>{setSlots(rows=>rows.filter((_,i)=>i!==index));invalidate();}}>Remove</button>}</div>)}{slots.length<5&&<button type="button" className="secondary" onClick={()=>{setSlots(rows=>[...rows,blankSlot()]);invalidate();}}>Add another time</button>}</fieldset>
    <button disabled={!!busy||venue==='PROVIDER_CONFERENCE'&&selected?.provider!=='GOOGLE'}>{busy==='preview'?'Rendering email…':'Preview email'}</button>
   </>}
  </form>}
  {preview&&draft&&<section className="email-preview" aria-label="Email preview"><h3>Review the delivered email</h3><dl><dt>From</dt><dd>{preview.from}</dd><dt>To</dt><dd>{preview.to}</dd><dt>Subject</dt><dd>{preview.subject}</dd></dl><iframe title="Actual invitation email" sandbox="" srcDoc={preview.html}/><div className="modal-actions"><button className="secondary" onClick={()=>setPreview(undefined)}>Edit invitation</button><button disabled={!!busy} onClick={send}>{busy==='send'?'Sending…':'Send invitation'}</button></div></section>}
 </Modal>;
}
